### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by jarvisyjw** [TongxingJin/TXTLCD#2]
Hi @TongxingJin,

Thanks for the great work. 

I am looking forward to using your proposed dataset. However, when I tried to download the dataset, the OneDrive seems to block me because I am not included in NTU's account. I think this might be a permission issue. Can you help to look into it?

Thanks,
Jingwen

**Comment by TongxingJin** [comment]
Hi @jarvisyjw,

I have tried from a remote server outside of NTU, sometimes it may encounter this problem. But I indeed have set the folder as public access, can you try again from github link? Or try this [new link](https://entuedu-my.sharepoint.com/:f:/g/personal/tongxing_jin_staff_main_ntu_edu_sg/Evw69kock4JBqy7G6DA_kDcBBKH-2je-iEY4tBfLOIYezw?e=hN7g6h)

Please let me know if the problem still exists. Thanks.

**Comment by jarvisyjw** [comment]
Hi @TongxingJin,

Thanks for the quick reply. The new link is working!

Jingwen

**Comment by jarvisyjw** [comment]
Hi @TongxingJin,

Is the textlcd_v1.tar the compressed version of all sequences?

Thanks,
Jingwen

**Comment by TongxingJin** [comment]
Hi @jarvisyjw,

No, it's the docker for OCR.
